#!/bin/bash

# This area is supoosed to be build.prop Configuration
# I suggest you to not modify this area if you know what you're doing.

# System Requirements
# For ARM BASED system (Linux ARM or Termux)
# ARMv8-a or aarch64 only

# For x86 Desktop:
# All CPU under i686 or x86-64/x64-86

# Delete
rm -rf rootfs/system/build.prop

# Cache
BUILD="rootfs/system/build.prop"

echo "# begin build properties" >> $BUILD
echo "# autogenerated by buildgen.sh" >> $BUILD
echo "ro.build.id=OC" >> $BUILD
echo "ro.build.display.id=OC test-keys" >> $BUILD
echo "ro.build.version.incremental=eng.root.20220310.183318" >> $BUILD
echo "ro.build.version.sdk=27" >> $BUILD 
echo "ro.build.version.preview_sdk=0" >> $BUILD # DO NOT CHANGE!
echo "ro.build.version.codename=REL" >> $BUILD
echo "ro.build.version.all_codenames=REL" >> $BUILD
echo "ro.build.version.release=8.1.0" >> $BUILD # DO NOT CHANGE
echo "ro.build.version.security_patch=2017-12-05" >> $BUILD 
echo "ro.build.version.base_os=" >> $BUILD # do not modify!
echo "ro.build.date=Thu Mar 10 18:33:18 WIB 2022" >> $BUILD
echo "ro.build.date.utc=1646911998" >> $BUILD
echo "ro.build.type=user" >> $BUILD # DO NOT MODIFY
echo "ro.build.usear=root" >> $BUILD # DO NOT MODIFY
echo "ro.build.host=aosp" >> $BUILD # DO NOT MODIFY
echo "ro.build.tags=test-keys" >> $BUILD #DO NOT MODIFY
echo "ro.build.flavor=twoyi_arm64-user" >> $BUILD # DO NOT MODIFY
read -r -p "What 'Model' Do you wanna call this? " answ
echo "ro.product.model=$answ" >> $BUILD
read -r -p "What 'Brand' Do you wanna call this? " answr
echo "ro.product.brand=$answr" >> $BUILD
echo "ro.product.name=twoyi_arm64" >> $BUILD
echo "ro.product.device=twoyi_arm64" >> $BUILD
if [ -e assets/buildfile_rest ]
then
cat assets/buildfile_rest >> $BUILD
./romfile.sh
else
echo "assets/buildfile_rest missing! Abort!"
rm -rf $BUILD 
exit 1
fi